### ISSUE TITLE
Missing configuration options

### ISSUE THREAD

**Issue by LemADEC** [Hypeirochus/Starcraft-Mod#1]
As of Starcraft-1.10.2-2.0.456, there's no configuration options for dimensions apart from Char and Shakuras.

**Comment by Hypeirochus** [comment]
Configuration options have been talked about in depth with various team members and fans. We will soon begin a drastic overhaul of the configuration file to allow for players to extensively change things about their game, such as dimension id's, creep spread speed, spawn rate intensity for structures, and so on. Thanks for bringing it to our attention even further. I'll leave this open until we have fulfilled our overhaul of the configuration file, to serve as a reminder.

**Comment by LemADEC** [comment]
Sounds like the fix won't land anytime soon.
Keep in mind it's difficult to make modpacks with mods forcing common id like dimension.

**Comment by Ocelot5836** [comment]
Will be fixed and redone in 1.12
