### ISSUE TITLE
Game freezes on loading into new world No crash occurs

### ISSUE THREAD

**Issue by DatrixTHLK** [Hypeirochus/Starcraft-Mod#5]
Hi,

When loading into an existing world or a new world the game will freeze up, but won't crash unless I force the Java program closed.

Minecraft: 1.12.2
Forge: 14.23.4.2747
Starcraft: 2.1.691

FML Log: https://gist.github.com/DatrixTHLK/b1aca72957d85f0132a72dbbd51072f5

If this has been mentioned already, then you can disregard. I didn't see any similar issues to this on the open issues in any case. I would love to try this mod out.

**Comment by Ocelot5836** [comment]
This error seems to be caused by Caverns II based on the log.

**Comment by DatrixTHLK** [comment]
Ok, I'll let the Caverns II modder know about this by linking the issue from there. Thanks!

**Comment by Ocelot5836** [comment]
Okay then
