### ISSUE TITLE
About your mod

### ISSUE THREAD

**Issue by wdog5** [Hypeirochus/Starcraft-Mod#8]
Dear Owner:

Hello,I have finished translating your mod now.I have created a paste bin with the zh_cn.lang.

The link:https://pastebin.com/XyppBmGU

If you don't want to, I will delete the translated file .
                                                                                                                                        Sincerely yours,

                                                                                                                                             179864396

**Comment by snakefangox** [comment]
Thank you very much for the translation! I'll get it merged as soon as I can.

**Comment by snakefangox** [comment]
I've merged your translations into the mod but I don't have the permissions to update the mod on sites like curseforge. I'll ask the one of the other devs to do so.
